// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAMt4rLwtm5htZhPZnWdT-bjyzGxnstPM',
    appId: '1:20423532374:web:213ad3f80bc841a9d880f7',
    messagingSenderId: '20423532374',
    projectId: 'zando-b574e',
    authDomain: 'zando-b574e.firebaseapp.com',
    storageBucket: 'zando-b574e.appspot.com',
    measurementId: 'G-SM7F64PL0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU0VQPo6mCA-o5DrGuCEhdhjG-AyCpeM8',
    appId: '1:20423532374:android:faa3e498bc1b1ceed880f7',
    messagingSenderId: '20423532374',
    projectId: 'zando-b574e',
    storageBucket: 'zando-b574e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7zkXAZ3HUm1MvWhTQ8lgUa74I6MGUyoE',
    appId: '1:20423532374:ios:096f7b56f4505e13d880f7',
    messagingSenderId: '20423532374',
    projectId: 'zando-b574e',
    storageBucket: 'zando-b574e.appspot.com',
    iosClientId: '20423532374-rluisdphm1tff82rujhfif91bgn3dtlp.apps.googleusercontent.com',
    iosBundleId: 'com.eshop.zando',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7zkXAZ3HUm1MvWhTQ8lgUa74I6MGUyoE',
    appId: '1:20423532374:ios:096f7b56f4505e13d880f7',
    messagingSenderId: '20423532374',
    projectId: 'zando-b574e',
    storageBucket: 'zando-b574e.appspot.com',
    iosClientId: '20423532374-rluisdphm1tff82rujhfif91bgn3dtlp.apps.googleusercontent.com',
    iosBundleId: 'com.eshop.zando',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAMt4rLwtm5htZhPZnWdT-bjyzGxnstPM',
    appId: '1:20423532374:web:061ffd5c00713fe8d880f7',
    messagingSenderId: '20423532374',
    projectId: 'zando-b574e',
    authDomain: 'zando-b574e.firebaseapp.com',
    storageBucket: 'zando-b574e.appspot.com',
    measurementId: 'G-1R3BLK0QGR',
  );
}
